### ISSUE TITLE
updatewcs

### ISSUE THREAD

**Issue by amn3142** [spacetelescope/stwcs#28]
Just installed the most recent astroconda build. This includes stwcs version 1.2.5, running with python 2.7.13. In the python terminal I try to run the following:

```python
     import stwcs
    from stwcs import updatewcs
    updatewcs.updatewcs(['fltname.fits'])
```

I get the following error:
``` 
LookupError: 
Problem finding row in IDCTAB! Could not find row matching:
        CHIP: 1
     FILTERS: F140W 
```

I have checked that my $iref and $jref values are set correctly and that the IDCTAB table listed in my flt header is in the $iref directory. 

Note that this problem does not occur when running the version with my old ureka installation, which had stwcs Version: 1.2.1.dev39127. With this older version I get the following output after running the same code as above:
    - IDCTAB: Distortion model from row 4 for chip 1 : F140W
    - IDCTAB: Distortion model from row 4 for chip 1 : F140W
    ['fltname.fits']

Which I assume means that everything worked.
